const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const label=value=>String(value).replaceAll('_',' ');
const scalarEntries=result=>Object.entries(result).filter(([,value])=>['string','number','boolean'].includes(typeof value)).slice(0,8);
function analysisCard(item){const metrics=scalarEntries(item.result).map(([key,value])=>`<div class="metric"><label>${esc(label(key))}</label><code>${esc(value)}</code></div>`).join('');return `<article class="analysis-card"><div class="analysis-head"><span class="analysis-name">${esc(label(item.processor))}</span><span class="${item.status==='ok'?'ok':'failed'}">${esc(item.status)}</span></div><div class="metric-grid">${metrics}</div></article>`}
function dataCard(name,value){return `<div class="data-card"><label>${esc(name)}</label><code>${esc(value)}</code></div>`}
function metric(value){const number=Number(value);return Number.isFinite(number)?number.toFixed(3):'n/a'}
async function loadModelEvidence(){const target=document.querySelector('#model-evidence'),badge=document.querySelector('#evidence-status');try{const response=await fetch('/api/v1/model/summary');if(response.status===404){badge.textContent='Trainable';return}if(!response.ok)throw new Error('model evidence unavailable');const payload=await response.json(),ext=payload.external_test||{};badge.textContent='Hash verified';target.innerHTML=[dataCard('External macro IoU',metric(ext.macro_iou)),dataCard('Weighted IoU',metric(ext.weighted_iou)),dataCard('Macro Dice',metric(ext.macro_dice)),dataCard('Calibration ECE',metric(ext.ece)),dataCard('External patches',ext.patches??'n/a'),dataCard('Showcase scene',payload.showcase_scene||'n/a'),dataCard('Model SHA-256',payload.model_sha256||'n/a'),dataCard('Dataset signature',payload.dataset_signature||'n/a')].join('')}catch(error){badge.textContent='Integrity/error';target.innerHTML='<div class="empty compact">Trained evidence failed verification or is unavailable.</div>'}}
async function load(){try{const [statusResponse,framesResponse]=await Promise.all([fetch('/api/v1/system/status'),fetch('/api/v1/frames?limit=1')]);if(!statusResponse.ok||!framesResponse.ok)throw new Error('API response failed');const status=await statusResponse.json(),frames=await framesResponse.json();document.querySelector('#status').textContent=`${Math.round(status.poll_interval_seconds/3600)} h poll · cloud ≤ ${status.max_cloud_cover}%`;document.querySelector('#model-mode').textContent=status.trained_landcover_bundle_present?'Trained model bundle':'Operational baselines';if(!frames.data.length)return;const frame=frames.data[0],meta=frame.metadata||{};document.querySelector('#visual').innerHTML=`<img id="earth" alt="Latest integrity-verified Sentinel-2 preview" src="${esc(frame.image_url)}"><div class="frame-title"><div><div class="eyebrow">Latest verified acquisition</div><h2>${esc(frame.captured_at)}</h2></div><span class="badge">${esc(meta.collection||frame.media_type)}</span></div>`;document.querySelector('#analysis').innerHTML=frame.analyses.map(analysisCard).join('')||'<div class="empty compact">Processing pending.</div>';const center=meta.centroid_coordinates?`${Number(meta.centroid_coordinates.lat).toFixed(4)}, ${Number(meta.centroid_coordinates.lon).toFixed(4)}`:'n/a';document.querySelector('#provenance').innerHTML=[dataCard('Source identifier',frame.source_id),dataCard('Cloud cover',meta.cloud_cover==null?'n/a':`${meta.cloud_cover}%`),dataCard('Centroid',center),dataCard('EPSG',meta.epsg||'n/a'),dataCard('SHA-256',frame.sha256),dataCard('Fetched at',frame.fetched_at),dataCard('Payload size',`${Number(frame.byte_size).toLocaleString()} bytes`)].join('')}catch(error){document.querySelector('#status').textContent='API unavailable'}finally{loadModelEvidence()}}
load();setInterval(load,60000);
